default_platform(:ios)

platform :ios do

  lane :custom_lane do

  end

  lane :certificates do
      register_devices(
      	devices_file: "./fastlane/devices.txt"
      )

      match(type: "development")
      match(type: "appstore")
  end
end
